# Generated by Django 4.2.6 on 2023-10-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_product_image_thumbnail_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='kabel.jpg', null=True, upload_to='images/'),
        ),
    ]
