# Generated by Django 4.2.6 on 2023-10-29 17:55

from django.db import migrations
import django_advance_thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_thumbnail',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, upload_to='images/thumbnails/'),
        ),
    ]
