# Generated by Django 4.2.6 on 2023-11-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0005_alter_product_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
